// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BarcodeScannerController from "./barcode_scanner_controller"
import HelloController from "./hello_controller"
import HorizontalBarcodeScannerController from "./horizontal_barcode_scanner_controller"
import SettingsFormController from "./settings_form_controller"

application.register("barcode-scanner", BarcodeScannerController)
application.register("hello", HelloController)
application.register("horizontal-barcode-scanner", HorizontalBarcodeScannerController)
application.register("settings-form", SettingsFormController)
